# Generated by Django 3.2 on 2021-04-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0002_auto_20210410_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameForm',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_first.post')),
            ],
            bases=('app_first.post',),
        ),
    ]
