# Generated by Django 3.2 on 2021-04-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0003_nameform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameForm',
        ),
    ]
