# Generated by Django 3.2.3 on 2021-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0008_auto_20210602_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
