# Generated by Django 3.2.3 on 2021-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0009_alter_tag_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
